<?php require_once('./templates/header.phtml'); ?>
        <form action="agregarProducto" method="POST">
            <h2>Agregar Producto:</h2>
            <div class="form-group">
                <label for="exampleInputEmail1">Imagen</label>
                <input type="text" name="img" class="form-control">
                <label for="exampleInputEmail1">Nombre</label>
                <input type="text" name="name" class="form-control">
                <label for="exampleInputEmail1">Descripcion</label>
                <input type="text" name="description" class="form-control">
                <label for="exampleInputEmail1">Precio</label>
                <input type="number" name="price" class="form-control">
                <?php
                ?>
            </div>
            <button type="submit" class="btn btn-primary">Agregar Producto</button>
        </form> 
        <?php require_once('./templates/footer.phtml'); ?>