<?php require_once('./templates/header.phtml'); ?>
<div class="container mt-5">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Season</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($categories as $category): ?>
            <tr>
                <td><?php echo $category->id ?></td>
                <td><?php echo $category->name_category ?></td>
                <td><?php echo $category->season ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php require_once('./templates/footer.phtml'); ?>