<?php require_once('./templates/header.phtml');?>
        <div class="card" style="width: 18rem;">
            <img src="<?php echo $product->img ?>" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Producto: <?php echo $product->name ?></h5>
                <h5 class="card-title">Descripción: <?php echo $product->description ?></h5>
                <h5 class="card-title">Precio: $ <?php echo $product->price ?></h5>
            </div>
        </div>
        <form action="actualizarProductoTotal" method="post">
        <input type="hidden" name="id" value="<?php echo $product->id; ?>">
                <label>Nombre del producto</label>
                <input type="text" name="name" class="form-control">
                <label>Descripcion del producto</label>
                <input type="text" name="description" class="form-control">
                <label>Precio del producto</label>
                <input type="text" name="price" class="form-control">
       
            <button type="submit" class="btn btn-primary">Actualizar</button>


        </form>

    <?php require_once('./templates/footer.phtml'); ?>