</main>
<footer class="navbar navbar-dark bg-dark navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <h4 class="navbar-brand">Footer Ecommerce</h4>
</nav>
  
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>
