<?php require_once('./templates/header.phtml'); ?>
        <form action="logged" method="POST">
        <h2>Ingresar:</h2>
            <div class="form-group">
                <label for="exampleInputEmail1">Usuario</label>
                <input type="text" name="user" class="form-control"  aria-describedby="Nombre de usuario">
                <small id="emailHelp" class="form-text text-muted">No compartas el tu usuario con nadie.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Contraseña</label>
                <input type="password" name="password" class="form-control" placeholder="Contraseña">
            </div>
           
            <button type="submit" class="btn btn-primary">Ingresar</button>
        </form>
        <?php require_once('./templates/footer.phtml'); ?>