<?php require_once('./templates/header.phtml'); ?>

<?php foreach($products as $product) : ?>
    <div class="card" style="width: 18rem;">
        <img src="<?php echo $product->img ?>" class="card-img-top" alt="imageProduct">
        <div class="card-body">
            <h5 class="card-title"><?php echo $product->name ?></h5>
            <a href="descripcion/<?php echo $product->id ?>" class="btn btn-primary">Ver detalles</a>
            <?php if (isset($_SESSION['user']) && ($_SESSION['logged'] == true) && ($_SESSION['rol'] == 'admin')) : ?>
                <a href="actualizarProducto/<?php echo $product->id ?>" class="btn btn-success">Actualizar producto</a>
            <?php endif ?>
        </div>
    </div>
<?php endforeach ?>

<?php require_once('./templates/footer.phtml'); ?>